USE anac_voos;
GO

-- January (imported via Import Flat File wizard in SSMS)

-- February
BULK INSERT fato_voos FROM 'C:\anac\VRA_20252.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- March
BULK INSERT fato_voos FROM 'C:\anac\VRA_20253.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- April
BULK INSERT fato_voos FROM 'C:\anac\VRA_20254.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- May
BULK INSERT fato_voos FROM 'C:\anac\VRA_20255.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- June
BULK INSERT fato_voos FROM 'C:\anac\VRA_20256.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- July
BULK INSERT fato_voos FROM 'C:\anac\VRA_20257.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- August
BULK INSERT fato_voos FROM 'C:\anac\VRA_20258.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- September
BULK INSERT fato_voos FROM 'C:\anac\VRA_20259.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- October
BULK INSERT fato_voos FROM 'C:\anac\VRA_202510.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- November
BULK INSERT fato_voos FROM 'C:\anac\VRA_202511.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');

-- December
BULK INSERT fato_voos FROM 'C:\anac\VRA_202512.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=';', ROWTERMINATOR='\n', TABLOCK, CODEPAGE='65001');
GO

SELECT COUNT(*) AS Total_Rows FROM fato_voos;
GO
